package com.example.localization

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    KHMER("km", "Khmer (ភាសាខ្មែរ)")
}

enum class StringKey {
    APP_NAME,
    GREETING_MORNING,
    GREETING_AFTERNOON,
    GREETING_EVENING,
    NAV_HOME,
    NAV_WORKOUT,
    NAV_PLANS,
    NAV_PROGRESS,
    NAV_PROFILE,
    NAV_SETTINGS,
    TODAYS_ACTIVITY,
    DAILY_PROGRESS,
    WORKOUT_STREAK,
    WORKOUTS_COUNT,
    ACTIVE_TIME,
    CALORIES_BURNED,
    DISTANCE_COVERED,
    QUICK_ACTIONS,
    ACTION_RUNNING,
    ACTION_WALKING,
    ACTION_JUMPING,
    ACTION_WEIGHTLIFTING,
    TODAYS_WORKOUT,
    NO_SCHEDULED_WORKOUT,
    START_WORKOUT,
    SLEEP_RECOVERY,
    LOG_SLEEP,
    SLEEP_DURATION,
    SLEEP_QUALITY,
    NUTRITION_SUMMARY,
    CALORIES,
    PROTEIN,
    CARBS,
    FAT,
    OF_TARGET,
    TARGET,
    CONSUMED,
    GUIDANCE_CONSISTENCY,
    GUIDANCE_REST_WELL,
    GUIDANCE_KEEP_GOING,
    WORKOUT_RUNNING,
    WORKOUT_WALKING,
    WORKOUT_JUMPING,
    WORKOUT_WEIGHTLIFTING,
    SESSION_START,
    SESSION_PAUSE,
    SESSION_RESUME,
    SESSION_FINISH,
    SESSION_CANCEL,
    PACE,
    CURRENT_PACE,
    AVG_PACE,
    SPEED,
    JUMP_COUNT,
    JUMPS,
    CALIBRATE_JUMP,
    TEST_JUMPS_REMAINING,
    CALIBRATION_COMPLETE,
    REST_TIMER,
    SKIP_REST,
    ADD_EXERCISE,
    ADD_SET,
    SET,
    REPS,
    WEIGHT,
    COMPLETED,
    VOLUME_TONNAGE,
    WORKOUT_PLANS,
    CREATE_PLAN,
    PLAN_NAME,
    DAYS_PER_WEEK,
    SESSION_DURATION_MINUTES,
    EQUIPMENT,
    OBJECTIVE,
    GENERATE_PLAN,
    FULL_GYM,
    DUMBBELLS_ONLY,
    BODYWEIGHT,
    STRENGTH,
    ENDURANCE,
    GENERAL_FITNESS,
    SCHEDULE_WORKOUT,
    REMINDER_OFFSET,
    TIME,
    DAY_OF_WEEK,
    ENABLED,
    FOOD_DATABASE,
    SEARCH_FOOD,
    ADD_CUSTOM_FOOD,
    PORTION_GRAMS,
    LOG_FOOD,
    BREAKFAST,
    LUNCH,
    SNACK,
    DINNER,
    CUSTOM_MEAL,
    WEEKLY_OVERVIEW,
    MONTHLY_OVERVIEW,
    LONGEST_STREAK,
    CURRENT_STREAK,
    TOTAL_DISTANCE,
    TOTAL_JUMPS,
    TOTAL_VOLUME,
    HISTORY,
    FILTER_ALL,
    FILTER_WORKOUTS,
    FILTER_NUTRITION,
    FILTER_SLEEP,
    SETTINGS,
    APPEARANCE,
    THEME_SYSTEM,
    THEME_DARK,
    THEME_LIGHT,
    LANGUAGE,
    UNITS,
    UNIT_METRIC,
    UNIT_IMPERIAL,
    NOTIFICATIONS,
    WORKOUT_REMINDERS,
    ABOUT_UPDATES,
    CURRENT_VERSION,
    CHECK_FOR_UPDATES,
    UPDATE_STATUS_UP_TO_DATE,
    UPDATE_STATUS_CHECKING,
    UPDATE_STATUS_AVAILABLE,
    UPDATE_NOW,
    RELEASE_NOTES,
    PROFILE,
    FULL_NAME,
    AGE,
    BIOLOGICAL_SEX,
    SEX_MALE,
    SEX_FEMALE,
    SEX_OTHER,
    HEIGHT,
    FITNESS_GOAL,
    ACTIVITY_LEVEL,
    SAVE_PROFILE,
    BMR_ESTIMATE,
    TDEE_ESTIMATE,
    CALORIE_TARGET,
    RESUME_ACTIVE_SESSION,
    DISCARD_ACTIVE_SESSION,
    SESSION_RECOVERED,
    OFFLINE_MODE,
    PERMISSION_LOCATION_REQUIRED,
    PERMISSION_NOTIFICATION_REQUIRED,
    DAILY_STEPS,
    STEP_TRACKING,
    STEP_TRACKING_ON,
    STEP_TRACKING_OFF,
    ACCOUNT_TITLE,
    ACCOUNT_OFFLINE_MODE,
    ACCOUNT_ONLINE_SYNCED,
    ACCOUNT_CONNECT_BTN,
    ACCOUNT_SYNC_NOW,
    ACCOUNT_LAST_SYNCED,
    ACCOUNT_SIGN_OUT,
    ACCOUNT_SIGN_IN_TITLE,
    ACCOUNT_SIGN_UP_TITLE,
    ACCOUNT_EMAIL_LABEL,
    ACCOUNT_PASSWORD_LABEL,
    ACCOUNT_NAME_LABEL,
    ACCOUNT_GOOGLE_SIGNIN,
    ACCOUNT_OFFLINE_DESC,
    ACCOUNT_SYNCING
}

object Localization {

    private val enStrings: Map<StringKey, String> = mapOf(
        StringKey.APP_NAME to "FITHUB",
        StringKey.GREETING_MORNING to "Good morning",
        StringKey.GREETING_AFTERNOON to "Good afternoon",
        StringKey.GREETING_EVENING to "Good evening",
        StringKey.NAV_HOME to "Home",
        StringKey.NAV_WORKOUT to "Workout",
        StringKey.NAV_PLANS to "Plans",
        StringKey.NAV_PROGRESS to "Progress",
        StringKey.NAV_PROFILE to "Profile",
        StringKey.NAV_SETTINGS to "Settings",
        StringKey.TODAYS_ACTIVITY to "Today's Activity",
        StringKey.DAILY_PROGRESS to "Daily Progress",
        StringKey.WORKOUT_STREAK to "Workout Streak",
        StringKey.WORKOUTS_COUNT to "Workouts",
        StringKey.ACTIVE_TIME to "Active Time",
        StringKey.CALORIES_BURNED to "Calories Burned",
        StringKey.DISTANCE_COVERED to "Distance Covered",
        StringKey.QUICK_ACTIONS to "Quick Actions",
        StringKey.ACTION_RUNNING to "Running",
        StringKey.ACTION_WALKING to "Walking",
        StringKey.ACTION_JUMPING to "Jumping",
        StringKey.ACTION_WEIGHTLIFTING to "Lifting",
        StringKey.TODAYS_WORKOUT to "Today's Routine",
        StringKey.NO_SCHEDULED_WORKOUT to "No routine scheduled for today",
        StringKey.START_WORKOUT to "Start Session",
        StringKey.SLEEP_RECOVERY to "Sleep & Recovery",
        StringKey.LOG_SLEEP to "Log Sleep",
        StringKey.SLEEP_DURATION to "Sleep Duration",
        StringKey.SLEEP_QUALITY to "Sleep Quality",
        StringKey.NUTRITION_SUMMARY to "Nutrition Target",
        StringKey.CALORIES to "Calories",
        StringKey.PROTEIN to "Protein",
        StringKey.CARBS to "Carbs",
        StringKey.FAT to "Fat",
        StringKey.OF_TARGET to "of target",
        StringKey.TARGET to "Target",
        StringKey.CONSUMED to "Consumed",
        StringKey.GUIDANCE_CONSISTENCY to "Consistent movement powers long-term physical conditioning.",
        StringKey.GUIDANCE_REST_WELL to "Adequate sleep and recovery maximize muscle rebuild.",
        StringKey.GUIDANCE_KEEP_GOING to "Every training session compounds your endurance and strength.",
        StringKey.WORKOUT_RUNNING to "Running Session",
        StringKey.WORKOUT_WALKING to "Walking Session",
        StringKey.WORKOUT_JUMPING to "Jump Rope Session",
        StringKey.WORKOUT_WEIGHTLIFTING to "Weightlifting Session",
        StringKey.SESSION_START to "Start",
        StringKey.SESSION_PAUSE to "Pause",
        StringKey.SESSION_RESUME to "Resume",
        StringKey.SESSION_FINISH to "Finish",
        StringKey.SESSION_CANCEL to "Cancel",
        StringKey.PACE to "Pace",
        StringKey.CURRENT_PACE to "Current Pace",
        StringKey.AVG_PACE to "Average Pace",
        StringKey.SPEED to "Speed",
        StringKey.JUMP_COUNT to "Jump Count",
        StringKey.JUMPS to "Jumps",
        StringKey.CALIBRATE_JUMP to "Calibrate Sensor",
        StringKey.TEST_JUMPS_REMAINING to "Perform 10 controlled jumps to calibrate",
        StringKey.CALIBRATION_COMPLETE to "Sensor calibration complete",
        StringKey.REST_TIMER to "Rest Interval",
        StringKey.SKIP_REST to "Skip Rest",
        StringKey.ADD_EXERCISE to "Add Exercise",
        StringKey.ADD_SET to "Add Set",
        StringKey.SET to "Set",
        StringKey.REPS to "Reps",
        StringKey.WEIGHT to "Weight",
        StringKey.COMPLETED to "Completed",
        StringKey.VOLUME_TONNAGE to "Session Volume",
        StringKey.WORKOUT_PLANS to "Workout Plans",
        StringKey.CREATE_PLAN to "Create Plan",
        StringKey.PLAN_NAME to "Plan Name",
        StringKey.DAYS_PER_WEEK to "Days Per Week",
        StringKey.SESSION_DURATION_MINUTES to "Duration (minutes)",
        StringKey.EQUIPMENT to "Equipment",
        StringKey.OBJECTIVE to "Objective",
        StringKey.GENERATE_PLAN to "Generate Plan",
        StringKey.FULL_GYM to "Full Gym",
        StringKey.DUMBBELLS_ONLY to "Dumbbells Only",
        StringKey.BODYWEIGHT to "Bodyweight",
        StringKey.STRENGTH to "Build Strength",
        StringKey.ENDURANCE to "Improve Endurance",
        StringKey.GENERAL_FITNESS to "General Fitness",
        StringKey.SCHEDULE_WORKOUT to "Schedule Routine",
        StringKey.REMINDER_OFFSET to "Reminder Notice",
        StringKey.TIME to "Time",
        StringKey.DAY_OF_WEEK to "Day of Week",
        StringKey.ENABLED to "Enabled",
        StringKey.FOOD_DATABASE to "Food Database",
        StringKey.SEARCH_FOOD to "Search foods",
        StringKey.ADD_CUSTOM_FOOD to "Add Custom Food",
        StringKey.PORTION_GRAMS to "Serving (g)",
        StringKey.LOG_FOOD to "Log Meal",
        StringKey.BREAKFAST to "Breakfast",
        StringKey.LUNCH to "Lunch",
        StringKey.SNACK to "Snack",
        StringKey.DINNER to "Dinner",
        StringKey.CUSTOM_MEAL to "Custom Meal",
        StringKey.WEEKLY_OVERVIEW to "Weekly Overview",
        StringKey.MONTHLY_OVERVIEW to "Monthly Overview",
        StringKey.LONGEST_STREAK to "Longest Streak",
        StringKey.CURRENT_STREAK to "Current Streak",
        StringKey.TOTAL_DISTANCE to "Total Distance",
        StringKey.TOTAL_JUMPS to "Total Jumps",
        StringKey.TOTAL_VOLUME to "Total Volume",
        StringKey.HISTORY to "History",
        StringKey.FILTER_ALL to "All",
        StringKey.FILTER_WORKOUTS to "Workouts",
        StringKey.FILTER_NUTRITION to "Nutrition",
        StringKey.FILTER_SLEEP to "Sleep",
        StringKey.SETTINGS to "Settings",
        StringKey.APPEARANCE to "Appearance",
        StringKey.THEME_SYSTEM to "System Default",
        StringKey.THEME_DARK to "Dark Mode",
        StringKey.THEME_LIGHT to "Light Mode",
        StringKey.LANGUAGE to "Language",
        StringKey.UNITS to "Units",
        StringKey.UNIT_METRIC to "Metric (kg, cm, km)",
        StringKey.UNIT_IMPERIAL to "Imperial (lbs, in, mi)",
        StringKey.NOTIFICATIONS to "Notifications",
        StringKey.WORKOUT_REMINDERS to "Workout Reminders",
        StringKey.ABOUT_UPDATES to "About and Updates",
        StringKey.CURRENT_VERSION to "Installed Version",
        StringKey.CHECK_FOR_UPDATES to "Check for Updates",
        StringKey.UPDATE_STATUS_UP_TO_DATE to "FITHUB is up to date",
        StringKey.UPDATE_STATUS_CHECKING to "Checking for updates...",
        StringKey.UPDATE_STATUS_AVAILABLE to "Update available",
        StringKey.UPDATE_NOW to "Update Now",
        StringKey.RELEASE_NOTES to "Release Notes",
        StringKey.PROFILE to "Profile",
        StringKey.FULL_NAME to "Full Name",
        StringKey.AGE to "Age",
        StringKey.BIOLOGICAL_SEX to "Biological Sex",
        StringKey.SEX_MALE to "Male",
        StringKey.SEX_FEMALE to "Female",
        StringKey.SEX_OTHER to "Other",
        StringKey.HEIGHT to "Height",
        StringKey.FITNESS_GOAL to "Fitness Goal",
        StringKey.ACTIVITY_LEVEL to "Activity Level",
        StringKey.SAVE_PROFILE to "Save Profile",
        StringKey.BMR_ESTIMATE to "Estimated BMR",
        StringKey.TDEE_ESTIMATE to "Estimated TDEE",
        StringKey.CALORIE_TARGET to "Daily Calorie Target",
        StringKey.RESUME_ACTIVE_SESSION to "Resume Active Session",
        StringKey.DISCARD_ACTIVE_SESSION to "Discard Session",
        StringKey.SESSION_RECOVERED to "Recovered active workout session",
        StringKey.OFFLINE_MODE to "Offline Mode",
        StringKey.PERMISSION_LOCATION_REQUIRED to "Location permission is required to track this activity.",
        StringKey.PERMISSION_NOTIFICATION_REQUIRED to "Notification permission is required for workout reminders.",
        StringKey.DAILY_STEPS to "Daily Steps",
        StringKey.STEP_TRACKING to "Step Tracking",
        StringKey.STEP_TRACKING_ON to "Active",
        StringKey.STEP_TRACKING_OFF to "Paused",
        StringKey.ACCOUNT_TITLE to "Cloud Account & Sync",
        StringKey.ACCOUNT_OFFLINE_MODE to "Offline Guest Mode",
        StringKey.ACCOUNT_ONLINE_SYNCED to "Cloud Synced",
        StringKey.ACCOUNT_CONNECT_BTN to "Sign In / Connect Cloud",
        StringKey.ACCOUNT_SYNC_NOW to "Sync Now",
        StringKey.ACCOUNT_LAST_SYNCED to "Last synced",
        StringKey.ACCOUNT_SIGN_OUT to "Sign Out",
        StringKey.ACCOUNT_SIGN_IN_TITLE to "Sign In to Fithub",
        StringKey.ACCOUNT_SIGN_UP_TITLE to "Create Cloud Account",
        StringKey.ACCOUNT_EMAIL_LABEL to "Email Address",
        StringKey.ACCOUNT_PASSWORD_LABEL to "Password",
        StringKey.ACCOUNT_NAME_LABEL to "Full Name",
        StringKey.ACCOUNT_GOOGLE_SIGNIN to "Continue with Google",
        StringKey.ACCOUNT_OFFLINE_DESC to "Your workout data is saved safely on your phone and works 100% offline.",
        StringKey.ACCOUNT_SYNCING to "Syncing with Cloud..."
    )

    private val kmStrings: Map<StringKey, String> = mapOf(
        StringKey.APP_NAME to "FITHUB",
        StringKey.GREETING_MORNING to "អរុណសួស្តី",
        StringKey.GREETING_AFTERNOON to "ទិវាសួស្តី",
        StringKey.GREETING_EVENING to "សាយ័ណ្ហសួស្តី",
        StringKey.NAV_HOME to "ទំព័រដើម",
        StringKey.NAV_WORKOUT to "ហាត់ប្រាណ",
        StringKey.NAV_PLANS to "គម្រោង",
        StringKey.NAV_PROGRESS to "វឌ្ឍនភាព",
        StringKey.NAV_PROFILE to "គណនី",
        StringKey.NAV_SETTINGS to "ការកំណត់",
        StringKey.TODAYS_ACTIVITY to "សកម្មភាពថ្ងៃនេះ",
        StringKey.DAILY_PROGRESS to "វឌ្ឍនភាពប្រចាំថ្ងៃ",
        StringKey.WORKOUT_STREAK to "ថ្ងៃហាត់ជាប់គ្នា",
        StringKey.WORKOUTS_COUNT to "ការហាត់",
        StringKey.ACTIVE_TIME to "ថិរវេលាសកម្ម",
        StringKey.CALORIES_BURNED to "កាឡូរីបានដុត",
        StringKey.DISTANCE_COVERED to "ចម្ងាយសរុប",
        StringKey.QUICK_ACTIONS to "សកម្មភាពរហ័ស",
        StringKey.ACTION_RUNNING to "រត់",
        StringKey.ACTION_WALKING to "ដើរ",
        StringKey.ACTION_JUMPING to "លោតខ្សែពួរ",
        StringKey.ACTION_WEIGHTLIFTING to "លើកទម្ងន់",
        StringKey.TODAYS_WORKOUT to "កម្មវិធីហាត់ថ្ងៃនេះ",
        StringKey.NO_SCHEDULED_WORKOUT to "គ្មានកម្មវិធីកំណត់សម្រាប់ថ្ងៃនេះទេ",
        StringKey.START_WORKOUT to "ចាប់ផ្តើមហាត់",
        StringKey.SLEEP_RECOVERY to "ដំណេក និងការស្តារកម្លាំង",
        StringKey.LOG_SLEEP to "កត់ត្រាដំណេក",
        StringKey.SLEEP_DURATION to "រយៈពេលគេង",
        StringKey.SLEEP_QUALITY to "គុណភាពដំណេក",
        StringKey.NUTRITION_SUMMARY to "គោលដៅអាហារូបត្ថម្ភ",
        StringKey.CALORIES to "កាឡូរី",
        StringKey.PROTEIN to "ប្រូតេអ៊ីន",
        StringKey.CARBS to "កាបូអ៊ីដ្រាត",
        StringKey.FAT to "ខ្លាញ់",
        StringKey.OF_TARGET to "នៃគោលដៅ",
        StringKey.TARGET to "គោលដៅ",
        StringKey.CONSUMED to "បានញ៉ាំ",
        StringKey.GUIDANCE_CONSISTENCY to "ការហាត់ប្រាណទៀងទាត់បង្កើតកម្លាំងកាយមាំមួនយូរអង្វែង។",
        StringKey.GUIDANCE_REST_WELL to "ដំណេកគ្រប់គ្រាន់ជួយស្តារសាច់ដុំឡើងវិញបានល្អបំផុត។",
        StringKey.GUIDANCE_KEEP_GOING to "រាល់ពេលហាត់ប្រាណជួយពង្រឹងកម្លាំងនិងភាពធន់របស់អ្នក។",
        StringKey.WORKOUT_RUNNING to "ការរត់",
        StringKey.WORKOUT_WALKING to "ការដើរ",
        StringKey.WORKOUT_JUMPING to "ការលោតខ្សែពួរ",
        StringKey.WORKOUT_WEIGHTLIFTING to "ការលើកទម្ងន់",
        StringKey.SESSION_START to "ចាប់ផ្តើម",
        StringKey.SESSION_PAUSE to "ផ្អាក",
        StringKey.SESSION_RESUME to "បន្ត",
        StringKey.SESSION_FINISH to "បញ្ចប់",
        StringKey.SESSION_CANCEL to "បោះបង់",
        StringKey.PACE to "ល្បឿនជាមធ្យម",
        StringKey.CURRENT_PACE to "ល្បឿនបច្ចុប្បន្ន",
        StringKey.AVG_PACE to "ល្បឿនមធ្យម",
        StringKey.SPEED to "ល្បឿន",
        StringKey.JUMP_COUNT to "ចំនួនលោត",
        StringKey.JUMPS to "ដង",
        StringKey.CALIBRATE_JUMP to "វាស់កម្រិតឧបករណ៍",
        StringKey.TEST_JUMPS_REMAINING to "សូមលោតសាកល្បង ១០ ដងដើម្បីវាស់កម្រិត",
        StringKey.CALIBRATION_COMPLETE to "ការវាស់កម្រិតឧបករណ៍បានជោគជ័យ",
        StringKey.REST_TIMER to "ពេលសម្រាក",
        StringKey.SKIP_REST to "រំលងសម្រាក",
        StringKey.ADD_EXERCISE to "បន្ថែមលំហាត់",
        StringKey.ADD_SET to "បន្ថែមឈុត",
        StringKey.SET to "ឈុត",
        StringKey.REPS to "លើក",
        StringKey.WEIGHT to "ទម្ងន់",
        StringKey.COMPLETED to "បានបញ្ចប់",
        StringKey.VOLUME_TONNAGE to "បរិមាណទម្ងន់សរុប",
        StringKey.WORKOUT_PLANS to "គម្រោងហាត់ប្រាណ",
        StringKey.CREATE_PLAN to "បង្កើតគម្រោង",
        StringKey.PLAN_NAME to "ឈ្មោះគម្រោង",
        StringKey.DAYS_PER_WEEK to "ចំនួនថ្ងៃក្នុងមួយសប្តាហ៍",
        StringKey.SESSION_DURATION_MINUTES to "រយៈពេល (នាទី)",
        StringKey.EQUIPMENT to "ឧបករណ៍",
        StringKey.OBJECTIVE to "គោលដៅ",
        StringKey.GENERATE_PLAN to "បង្កើតគម្រោងស្វ័យប្រវត្តិ",
        StringKey.FULL_GYM to "កន្លែងហាត់ប្រាណពេញលេញ",
        StringKey.DUMBBELLS_ONLY to "ដុំដែកដៃតែប៉ុណ្ណោះ",
        StringKey.BODYWEIGHT to "ទម្ងន់ខ្លួនសុទ្ធ",
        StringKey.STRENGTH to "ពង្រឹងសាច់ដុំ",
        StringKey.ENDURANCE to "បង្កើនភាពធន់",
        StringKey.GENERAL_FITNESS to "សុខភាពទូទៅ",
        StringKey.SCHEDULE_WORKOUT to "កាលវិភាគហាត់ប្រាណ",
        StringKey.REMINDER_OFFSET to "ពេលរំលឹកមុន",
        StringKey.TIME to "ម៉ោង",
        StringKey.DAY_OF_WEEK to "ថ្ងៃនៃសប្តាហ៍",
        StringKey.ENABLED to "បើកដំណើរការ",
        StringKey.FOOD_DATABASE to "ទិន្នន័យអាហារ",
        StringKey.SEARCH_FOOD to "ស្វែងរកអាហារ",
        StringKey.ADD_CUSTOM_FOOD to "បន្ថែមអាហារថ្មី",
        StringKey.PORTION_GRAMS to "បរិមាណ (ក្រាម)",
        StringKey.LOG_FOOD to "កត់ត្រាអាហារ",
        StringKey.BREAKFAST to "អាហារពេលព្រឹក",
        StringKey.LUNCH to "អាហារថ្ងៃត្រង់",
        StringKey.SNACK to "អាហារសម្រន់",
        StringKey.DINNER to "អាហារពេលល្ងាច",
        StringKey.CUSTOM_MEAL to "អាហារផ្សេងៗ",
        StringKey.WEEKLY_OVERVIEW to "ទិដ្ឋភាពប្រចាំសប្តាហ៍",
        StringKey.MONTHLY_OVERVIEW to "ទិដ្ឋភាពប្រចាំខែ",
        StringKey.LONGEST_STREAK to "ថ្ងៃហាត់ជាប់គ្នាយូរបំផុត",
        StringKey.CURRENT_STREAK to "ថ្ងៃហាត់ជាប់គ្នាបច្ចុប្បន្ន",
        StringKey.TOTAL_DISTANCE to "ចម្ងាយសរុប",
        StringKey.TOTAL_JUMPS to "ចំនួនលោតសរុប",
        StringKey.TOTAL_VOLUME to "ទម្ងន់សរុប",
        StringKey.HISTORY to "ប្រវត្តិ",
        StringKey.FILTER_ALL to "ទាំងអស់",
        StringKey.FILTER_WORKOUTS to "ការហាត់",
        StringKey.FILTER_NUTRITION to "អាហារ",
        StringKey.FILTER_SLEEP to "ដំណេក",
        StringKey.SETTINGS to "ការកំណត់",
        StringKey.APPEARANCE to "រូបរាង",
        StringKey.THEME_SYSTEM to "តាមប្រព័ន្ធទូរស័ព្ទ",
        StringKey.THEME_DARK to "ផ្ទៃងងឹត",
        StringKey.THEME_LIGHT to "ផ្ទៃភ្លឺ",
        StringKey.LANGUAGE to "ភាសា",
        StringKey.UNITS to "ខ្នាតរង្វាស់",
        StringKey.UNIT_METRIC to "ខ្នាតម៉ែត្រ (kg, cm, km)",
        StringKey.UNIT_IMPERIAL to "ខ្នាតអង់គ្លេស (lbs, in, mi)",
        StringKey.NOTIFICATIONS to "ការជូនដំណឹង",
        StringKey.WORKOUT_REMINDERS to "រំលឹកការហាត់ប្រាណ",
        StringKey.ABOUT_UPDATES to "ព័ត៌មាននិងកំណែថ្មី",
        StringKey.CURRENT_VERSION to "កំណែបច្ចុប្បន្ន",
        StringKey.CHECK_FOR_UPDATES to "ពិនិត្យមើលកំណែថ្មី",
        StringKey.UPDATE_STATUS_UP_TO_DATE to "FITHUB ស្ថិតក្នុងកំណែចុងក្រោយហើយ",
        StringKey.UPDATE_STATUS_CHECKING to "កំពុងពិនិត្យមើលកំណែថ្មី...",
        StringKey.UPDATE_STATUS_AVAILABLE to "មានកំណែថ្មីដែលអាចទាញយកបាន",
        StringKey.UPDATE_NOW to "ធ្វើបច្ចុប្បន្នភាពឥឡូវនេះ",
        StringKey.RELEASE_NOTES to "កំណត់សម្គាល់កំណែ",
        StringKey.PROFILE to "គណនីផ្ទាល់ខ្លួន",
        StringKey.FULL_NAME to "ឈ្មោះពេញ",
        StringKey.AGE to "អាយុ",
        StringKey.BIOLOGICAL_SEX to "ភេទ",
        StringKey.SEX_MALE to "ប្រុស",
        StringKey.SEX_FEMALE to "ស្រី",
        StringKey.SEX_OTHER to "ផ្សេងទៀត",
        StringKey.HEIGHT to "កម្ពស់",
        StringKey.FITNESS_GOAL to "គោលដៅហាត់ប្រាណ",
        StringKey.ACTIVITY_LEVEL to "កម្រិតសកម្មភាព",
        StringKey.SAVE_PROFILE to "រក្សាទុកព័ត៌មាន",
        StringKey.BMR_ESTIMATE to "BMR ប៉ាន់ស្មាន",
        StringKey.TDEE_ESTIMATE to "TDEE ប៉ាន់ស្មាន",
        StringKey.CALORIE_TARGET to "គោលដៅកាឡូរីប្រចាំថ្ងៃ",
        StringKey.RESUME_ACTIVE_SESSION to "បន្តការហាត់ដែលនៅសល់",
        StringKey.DISCARD_ACTIVE_SESSION to "លុបចោលការហាត់ចាស់",
        StringKey.SESSION_RECOVERED to "បានរកឃើញការហាត់ដែលមិនទាន់បានបញ្ចប់",
        StringKey.OFFLINE_MODE to "ដំណើរការក្រៅបណ្តាញ",
        StringKey.PERMISSION_LOCATION_REQUIRED to "ត្រូវការការអនុញ្ញាតទីតាំង ដើម្បីវាស់ចម្ងាយសកម្មភាពនេះ។",
        StringKey.PERMISSION_NOTIFICATION_REQUIRED to "ត្រូវការការអនុញ្ញាតជូនដំណឹង សម្រាប់រំលឹកការហាត់ប្រាណ។",
        StringKey.DAILY_STEPS to "ជំហានដើរប្រចាំថ្ងៃ",
        StringKey.STEP_TRACKING to "តាមដានការដើរ",
        StringKey.STEP_TRACKING_ON to "កំពុងដំណើរការ",
        StringKey.STEP_TRACKING_OFF to "បានបិទ",
        StringKey.ACCOUNT_TITLE to "គណនី Cloud & ការ Sync",
        StringKey.ACCOUNT_OFFLINE_MODE to "របៀបក្រៅបណ្តាញ (ភ្ញៀវ)",
        StringKey.ACCOUNT_ONLINE_SYNCED to "បាន Sync លើ Cloud",
        StringKey.ACCOUNT_CONNECT_BTN to "ចូលប្រើ / ភ្ជាប់គណនី Cloud",
        StringKey.ACCOUNT_SYNC_NOW to "Sync ឥឡូវនេះ",
        StringKey.ACCOUNT_LAST_SYNCED to "Sync ចុងក្រោយ",
        StringKey.ACCOUNT_SIGN_OUT to "ចាកចេញពីគណនី",
        StringKey.ACCOUNT_SIGN_IN_TITLE to "ចូលប្រើប្រាស់ Fithub",
        StringKey.ACCOUNT_SIGN_UP_TITLE to "បង្កើតគណនី Cloud ថ្មី",
        StringKey.ACCOUNT_EMAIL_LABEL to "អាសយដ្ឋាន Email",
        StringKey.ACCOUNT_PASSWORD_LABEL to "ពាក្យសម្ងាត់",
        StringKey.ACCOUNT_NAME_LABEL to "ឈ្មោះពេញ",
        StringKey.ACCOUNT_GOOGLE_SIGNIN to "បន្តជាមួយ Google",
        StringKey.ACCOUNT_OFFLINE_DESC to "ទិន្នន័យរបស់អ្នកត្រូវបានរក្សាទុកលើទូរសព្ទដោយសុវត្ថិភាព និងដំណើរការក្រៅបណ្តាញ ១០០%។",
        StringKey.ACCOUNT_SYNCING to "កំពុង Sync ជាមួយ Cloud..."
    )

    fun getString(key: StringKey, language: AppLanguage): String {
        return when (language) {
            AppLanguage.ENGLISH -> enStrings[key] ?: key.name
            AppLanguage.KHMER -> kmStrings[key] ?: enStrings[key] ?: key.name
        }
    }
}
